import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "npm:@supabase/supabase-js@^2.95.0/cors";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
const configured=(name:string,dict:string)=>{const direct=Deno.env.get(name);if(direct)return direct;try{const d=JSON.parse(Deno.env.get(dict)??"{}");if(d&&typeof d==='object')return Object.values(d).find(v=>typeof v==='string'&&v) as string|undefined}catch{}return undefined};
const pub=()=>configured('SUPABASE_PUBLISHABLE_KEY','SUPABASE_PUBLISHABLE_KEYS')??Deno.env.get('SUPABASE_ANON_KEY')??'';const secret=()=>configured('SUPABASE_SECRET_KEY','SUPABASE_SECRET_KEYS')??Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
async function ctx(req:Request){const h=req.headers.get('Authorization');if(!h)throw new Response('Authorization required',{status:401});const token=h.replace(/^Bearer\s+/i,'');const url=Deno.env.get('SUPABASE_URL')??'';const key=pub();if(!url||!key)throw new Response('Supabase runtime configuration is incomplete',{status:500});const sb=createClient(url,key,{global:{headers:{Authorization:h}},auth:{persistSession:false,autoRefreshToken:false}});const{data:{user},error}=await sb.auth.getUser(token);if(error||!user)throw new Response('Invalid or expired session',{status:401});const{data:profile,error:pe}=await sb.from('metabolic_profiles').select('*').eq('user_id',user.id).maybeSingle();if(pe)throw pe;if(!profile||profile.status!=='ACTIVE')throw new Response('LIVYA account is not active',{status:403});return{sb,user,profile}}
const admin=()=>{const k=secret(),u=Deno.env.get('SUPABASE_URL')??'';if(!u||!k)throw new Error('Server admin key is not configured');return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})};const reqAdmin=(p:any)=>{if(p.role!=='ADMIN'||p.status!=='ACTIVE')throw new Response('Administrator access required',{status:403})};const KEYS=['clients.view','clients.manage','reports.view','reports.manage','checkins.view','checkins.manage','notes.view','notes.manage','programs.view','programs.manage','diet.view','diet.manage','recipes.view','recipes.manage','files.view','files.manage','messages.view','messages.manage','audit.view'];const perms=(x:any)=>Object.fromEntries(KEYS.map(k=>[k,x?.[k]===true]));
function fail(e:unknown){if(e instanceof Response)return e;console.error('[LIVYA metabolic-api]',e);return json({error:e instanceof Error?e.message:'Unexpected server error'},500)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{const{sb,user,profile}=await ctx(req);const route=new URL(req.url).pathname.replace(/^\/functions\/v1\/metabolic-api/,'').replace(/^\/+/,'');
if(!route||route==='me')return json({user:{id:user.id,email:user.email},profile});
if(route==='clients'&&req.method==='GET'){const{data,error}=await sb.from('metabolic_clients').select('*').order('full_name');if(error)throw error;return json({data})}
if(route==='dashboard'&&req.method==='GET'){const qs=await Promise.all(['metabolic_clients','metabolic_reports','metabolic_checkins','metabolic_notes'].map(t=>sb.from(t).select('id',{count:'exact',head:true})));for(const q of qs)if(q.error)throw q.error;return json({clients:qs[0].count??0,reports:qs[1].count??0,checkins:qs[2].count??0,notes:qs[3].count??0})}
if(route==='staff'&&req.method==='GET'){reqAdmin(profile);const a=admin();const{data:p,error}=await a.from('metabolic_profiles').select('user_id,full_name,phone,job_title,role,status,created_at,updated_at,hims_user_id').in('role',['ADMIN','SUB_ADMIN']).order('full_name');if(error)throw error;const ids=(p??[]).map(x=>x.user_id);const{data:s,error:se}=ids.length?await a.from('metabolic_staff_permissions').select('user_id,permissions,updated_at').in('user_id',ids):{data:[],error:null};if(se)throw se;const m=new Map((s??[]).map(x=>[x.user_id,x.permissions??{}]));return json({data:(p??[]).map(x=>({...x,permissions:m.get(x.user_id)??{}}))})}
if(route==='staff'&&req.method==='POST'){reqAdmin(profile);const b=await req.json();const name=String(b.fullName??'').trim(),email=String(b.email??'').trim().toLowerCase(),phone=String(b.phone??'').trim(),title=String(b.jobTitle??'Staff').trim()||'Staff',password=String(b.password??'');if(!name||!email||password.length<8)return json({error:'fullName, email and password of at least 8 characters are required'},400);const a=admin();const{data:c,error:ce}=await a.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:name,role:'SUB_ADMIN',job_title:title}});if(ce)throw ce;const id=c.user?.id;if(!id)throw new Error('Auth user was not created');const{error:pe}=await a.from('metabolic_profiles').insert({user_id:id,full_name:name,phone,job_title:title,role:'SUB_ADMIN',status:'ACTIVE'});if(pe){await a.auth.admin.deleteUser(id);throw pe}const{error:se}=await a.from('metabolic_staff_permissions').insert({user_id:id,permissions:perms(b.permissions)});if(se){await a.auth.admin.deleteUser(id);throw se}return json({ok:true,userId:id})}
if(route==='staff'&&req.method==='PATCH'){reqAdmin(profile);const b=await req.json(),id=String(b.userId??'');if(!id||id===user.id)return json({error:'A different employee account is required'},400);const a=admin();const{data:t,error:te}=await a.from('metabolic_profiles').select('user_id,role').eq('user_id',id).single();if(te)throw te;if(t.role==='ADMIN')return json({error:'Administrator accounts cannot be changed here'},400);const u:any={};if(b.fullName!=null)u.full_name=String(b.fullName).trim();if(b.phone!=null)u.phone=String(b.phone).trim();if(b.jobTitle!=null)u.job_title=String(b.jobTitle).trim();if(b.status!=null){const st=String(b.status).toUpperCase();if(!['ACTIVE','INACTIVE'].includes(st))return json({error:'Invalid staff status'},400);u.status=st}if(Object.keys(u).length){const{error}=await a.from('metabolic_profiles').update(u).eq('user_id',id);if(error)throw error}if(b.permissions!=null){const{error}=await a.from('metabolic_staff_permissions').upsert({user_id:id,permissions:perms(b.permissions),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error}if(b.password!=null){const pw=String(b.password);if(pw.length<8)return json({error:'Password must be at least 8 characters'},400);const{error}=await a.auth.admin.updateUserById(id,{password:pw});if(error)throw error}if(b.status!=null){const st=String(b.status).toUpperCase();const{error}=await a.auth.admin.updateUserById(id,{ban_duration:st==='INACTIVE'?'876000h':'none'});if(error)throw error}return json({ok:true,userId:id})}
if(route==='client-account'&&req.method==='POST'){reqAdmin(profile);const b=await req.json(),clientId=String(b.clientId??''),email=String(b.email??'').trim().toLowerCase(),password=String(b.password??'');if(!clientId||!email||password.length<8)return json({error:'clientId, email and password of at least 8 characters are required'},400);const a=admin();const{data:r,error:re}=await a.from('metabolic_clients').select('id,full_name,phone,client_user_id').eq('id',clientId).single();if(re)throw re;let id=r.client_user_id;if(!id){const{data:c,error}=await a.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:r.full_name,role:'CLIENT'}});if(error)throw error;id=c.user?.id}else{const{error}=await a.auth.admin.updateUserById(id,{email,password});if(error)throw error}if(!id)throw new Error('Auth user was not created');const{error:pe}=await a.from('metabolic_profiles').upsert({user_id:id,full_name:r.full_name,role:'CLIENT',phone:r.phone||'',job_title:'Client',status:'ACTIVE'},{onConflict:'user_id'});if(pe)throw pe;const{error:le}=await a.from('metabolic_clients').update({client_user_id:id,email}).eq('id',clientId);if(le)throw le;return json({ok:true,userId:id,clientId})}
if(route==='client-account'&&req.method==='PATCH'){reqAdmin(profile);const b=await req.json(),id=String(b.userId??''),status=String(b.status??'ACTIVE').toUpperCase();if(!id||!['ACTIVE','INACTIVE'].includes(status))return json({error:'userId and valid status are required'},400);const a=admin();const{error}=await a.from('metabolic_profiles').update({status}).eq('user_id',id);if(error)throw error;const{error:ae}=await a.auth.admin.updateUserById(id,{ban_duration:status==='INACTIVE'?'876000h':'none'});if(ae)throw ae;return json({ok:true,userId:id,status})}
return json({error:'Route not found'},404)}catch(e){return fail(e)}});