/* LIVYA Metabolic Reset embedded module. */
(function(){
  'use strict';
  const APP_PATH='metabolic/index.html';
  const SUPABASE_STORAGE_KEY='sb-weqghrrvgunfpsvtrlkw-auth-token';
  let frame,overlay;
  async function getHimsSession(){try{const client=window.__LIVYA_SB||window.__LIVYA_HIMS_SUPABASE;if(client?.auth?.getSession){const r=await client.auth.getSession();return r?.data?.session||null}}catch(e){console.warn('[LIVYA] Could not read HIMS auth session',e)}return null}
  async function seedSession(){const s=await getHimsSession();if(!s?.access_token||!s?.refresh_token)return null;try{const serialized=JSON.stringify(s);localStorage.setItem('livya-metabolic-auth',serialized);localStorage.setItem(SUPABASE_STORAGE_KEY,serialized)}catch(e){}return s}
  function selectedHimsPatientId(){const node=document.querySelector('.selected-patient');const m=(node?.textContent||'').match(/Selected patient:\s*([^\s<]+)/i);return m?m[1].trim():null}
  async function applyPatientContext(){const patientId=selectedHimsPatientId();if(!patientId||!frame?.contentWindow)return false;try{const client=frame.contentWindow.LIVYA_BACKEND?.client;if(!client)return false;const r=await client.from('metabolic_clients').select('id,full_name').eq('hims_patient_id',patientId).maybeSingle();if(r?.error||!r?.data)return false;const id=JSON.stringify(r.data.id);frame.contentWindow.eval(`if(typeof UI!=='undefined'){UI.clientId=${id};UI.view='health';if(typeof render==='function')render();}`);frame.contentWindow.postMessage({type:'LIVYA_HIMS_PATIENT_CONTEXT',himsPatientId:patientId,metabolicClientId:r.data.id},location.origin);return true}catch(e){console.warn('[LIVYA] Patient context handoff failed',e);return false}}
  async function syncFrameSession(){if(!frame?.contentWindow)return false;const session=await seedSession();if(!session)return false;for(let i=0;i<60;i++){try{const backend=frame.contentWindow.LIVYA_BACKEND;const client=backend?.client;if(client?.auth?.setSession){const r=await client.auth.setSession({access_token:session.access_token,refresh_token:session.refresh_token});if(!r?.error)return true}}catch(e){}await new Promise(r=>setTimeout(r,100))}return false}
  async function clearFrameSession(){try{await frame?.contentWindow?.LIVYA_BACKEND?.client?.auth?.signOut()}catch(e){}try{localStorage.removeItem('livya-metabolic-auth');localStorage.removeItem(SUPABASE_STORAGE_KEY)}catch(e){}}
  function ensure(){if(document.getElementById('metabolicNavBtn'))return;const nav=document.querySelector('.nav');if(!nav)return;const b=document.createElement('button');b.id='metabolicNavBtn';b.type='button';b.title='Metabolic Reset';b.textContent='Metabolic Reset';b.onclick=open;nav.appendChild(b)}
  async function open(){const session=await seedSession();if(!session){console.warn('[LIVYA] Metabolic Reset blocked because HIMS has no active session');return}if(!overlay){overlay=document.createElement('div');overlay.id='metabolicModuleOverlay';overlay.innerHTML='<div class="metabolic-module-frame"><div class="metabolic-module-bar"><div class="metabolic-module-title">LIVYA <span>Metabolic Reset</span></div><button class="metabolic-module-close" type="button">Close</button></div><iframe id="metabolicModuleFrame" title="LIVYA Metabolic Reset"></iframe></div>';document.body.appendChild(overlay);frame=overlay.querySelector('#metabolicModuleFrame');overlay.querySelector('.metabolic-module-close').onclick=close;overlay.addEventListener('click',e=>{if(e.target===overlay)close()});frame.addEventListener('load',async()=>{await syncFrameSession();await new Promise(r=>setTimeout(r,150));await applyPatientContext()})}overlay.classList.add('show');if(!frame.src||!frame.src.endsWith('/'+APP_PATH))frame.src=APP_PATH;else{await syncFrameSession();await applyPatientContext()}}
  function close(){if(overlay)overlay.classList.remove('show')}
  function bindLogout(){document.addEventListener('click',e=>{const logout=e.target?.closest?.('#logout');if(logout)clearFrameSession()},true)}
  function start(){const css=document.createElement('link');css.rel='stylesheet';css.href='metabolic-module.css?v=4';document.head.appendChild(css);const font=document.createElement('link');font.rel='stylesheet';font.href='https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600;700&display=swap';document.head.appendChild(font);ensure();bindLogout();const observer=new MutationObserver(ensure);if(document.body)observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),180000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.LIVYA_METABOLIC_MODULE={open,close,clearSession:clearFrameSession,applyPatientContext};
})();