-- GIMS v1: internal stores / procurement / inventory workflow
create extension if not exists pgcrypto;

create table if not exists public.gims_user_roles(
  email text primary key,
  full_name text not null,
  role text not null check(role in('admin','manager','operator','management','requester')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.gims_user_roles(email,full_name,role) values
('gearsganesh@gmail.com','Ganesh','admin'),
('jaiganesh@curesectors.in','Jaiganesh','operator'),
('nirmalkumar.rc1@gmail.com','Nirmal','manager'),
('vktraju@curesectors.in','VKT Raju','management'),
('sachin@curesectors.in','Sachin','operator')
on conflict(email) do update set full_name=excluded.full_name,role=excluded.role,active=true;

create table if not exists public.gims_items(id uuid primary key default gen_random_uuid(),item_code text not null unique,item_name text not null,description text,category text,supplier_id uuid,reorder_level numeric not null default 0,minimum_stock numeric not null default 0,unit text not null default 'EA',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.gims_suppliers(id uuid primary key default gen_random_uuid(),supplier_code text unique,supplier_name text not null,contact_person text,mobile text,email text,address text,gstin text,payment_terms text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.gims_purchase_orders(id uuid primary key default gen_random_uuid(),po_number text not null unique,supplier_id uuid references public.gims_suppliers(id),requested_by text,facility text,po_date date not null default current_date,expected_delivery_date date,status text not null default 'DRAFT' check(status in('DRAFT','SUBMITTED','APPROVED','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),subtotal numeric not null default 0,discount numeric not null default 0,tax numeric not null default 0,grand_total numeric not null default 0,notes text,created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.gims_purchase_order_items(id uuid primary key default gen_random_uuid(),po_id uuid not null references public.gims_purchase_orders(id) on delete cascade,item_id uuid not null references public.gims_items(id),quantity numeric not null check(quantity>0),unit_rate numeric not null default 0,discount numeric not null default 0,tax numeric not null default 0,line_total numeric not null default 0);
create table if not exists public.gims_goods_receipts(id uuid primary key default gen_random_uuid(),grn_number text not null unique,po_id uuid references public.gims_purchase_orders(id),supplier_id uuid references public.gims_suppliers(id),invoice_number text,invoice_date date,received_by text,received_at timestamptz not null default now(),notes text);
create table if not exists public.gims_goods_receipt_items(id uuid primary key default gen_random_uuid(),grn_id uuid not null references public.gims_goods_receipts(id) on delete cascade,po_item_id uuid references public.gims_purchase_order_items(id),item_id uuid not null references public.gims_items(id),ordered_qty numeric not null default 0,received_qty numeric not null default 0,rejected_qty numeric not null default 0,accepted_qty numeric not null default 0,batch_no text,expiry_date date);
create table if not exists public.gims_stock_balances(item_id uuid primary key references public.gims_items(id) on delete cascade,quantity numeric not null default 0,updated_at timestamptz not null default now());
create table if not exists public.gims_stock_transactions(id uuid primary key default gen_random_uuid(),item_id uuid not null references public.gims_items(id),transaction_type text not null check(transaction_type in('OPENING_STOCK','PURCHASE','DISPATCH','ADJUSTMENT_IN','ADJUSTMENT_OUT','RETURN','DAMAGE')),quantity numeric not null,reference_type text,reference_id uuid,reference_number text,performed_by text,notes text,created_at timestamptz not null default now());
create table if not exists public.gims_requests(id uuid primary key default gen_random_uuid(),request_number text not null unique,request_type text not null check(request_type in('EXISTING_ITEM','NEW_PROCUREMENT')),requested_by text not null,requester_email text,facility text,department text,purpose text,priority text not null default 'NORMAL' check(priority in('LOW','NORMAL','HIGH','URGENT')),required_date date,status text not null default 'SUBMITTED' check(status in('DRAFT','SUBMITTED','UNDER_REVIEW','PARTIALLY_APPROVED','APPROVED','REJECTED','PARTIALLY_DISPATCHED','DISPATCHED','RECEIVED','COMPLETED','CANCELLED')),notes text,procurement_description text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.gims_request_items(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.gims_requests(id) on delete cascade,item_id uuid references public.gims_items(id),requested_item_name text,requested_description text,requested_qty numeric not null check(requested_qty>0),approved_qty numeric not null default 0,dispatched_qty numeric not null default 0,remarks text);
create table if not exists public.gims_dispatches(id uuid primary key default gen_random_uuid(),dispatch_number text not null unique,request_id uuid references public.gims_requests(id),dispatched_by text,dispatched_at timestamptz not null default now(),received_by text,received_at timestamptz,facility text,notes text,status text not null default 'DISPATCHED' check(status in('DISPATCHED','RECEIVED','CANCELLED')));
create table if not exists public.gims_dispatch_items(id uuid primary key default gen_random_uuid(),dispatch_id uuid not null references public.gims_dispatches(id) on delete cascade,item_id uuid not null references public.gims_items(id),approved_qty numeric not null default 0,dispatched_qty numeric not null default 0);
create table if not exists public.gims_audit_log(id uuid primary key default gen_random_uuid(),actor_email text,actor_name text,action text not null,entity_type text,entity_id uuid,details jsonb,created_at timestamptz not null default now());
create or replace function public.gims_role() returns text language sql stable security definer set search_path=public as $$ select role from public.gims_user_roles where lower(email)=lower(coalesce(auth.jwt()->>'email','')) and active=true limit 1 $$;
create or replace function public.gims_allowed() returns boolean language sql stable security definer set search_path=public as $$ select public.gims_role() is not null $$;
DO $$ declare t text; begin foreach t in array array['gims_user_roles','gims_items','gims_suppliers','gims_purchase_orders','gims_purchase_order_items','gims_goods_receipts','gims_goods_receipt_items','gims_stock_balances','gims_stock_transactions','gims_requests','gims_request_items','gims_dispatches','gims_dispatch_items','gims_audit_log'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
drop policy if exists gims_roles_self on public.gims_user_roles;
create policy gims_roles_self on public.gims_user_roles for select to authenticated using(lower(email)=lower(coalesce(auth.jwt()->>'email','')) or public.gims_role()='admin');
DO $$ declare t text; begin foreach t in array array['gims_items','gims_suppliers','gims_purchase_orders','gims_purchase_order_items','gims_goods_receipts','gims_goods_receipt_items','gims_stock_balances','gims_stock_transactions','gims_requests','gims_request_items','gims_dispatches','gims_dispatch_items','gims_audit_log'] loop execute format('drop policy if exists %I_select on public.%I',t,t); execute format('create policy %I_select on public.%I for select to authenticated using(public.gims_allowed())',t,t); execute format('drop policy if exists %I_insert on public.%I',t,t); execute format('create policy %I_insert on public.%I for insert to authenticated with check(public.gims_allowed())',t,t); execute format('drop policy if exists %I_update on public.%I',t,t); execute format('create policy %I_update on public.%I for update to authenticated using(public.gims_allowed()) with check(public.gims_allowed())',t,t); end loop; end $$;
create index if not exists idx_gims_items_name on public.gims_items(item_name);
create index if not exists idx_gims_requests_status on public.gims_requests(status);
create index if not exists idx_gims_stock_tx_item on public.gims_stock_transactions(item_id,created_at desc);
insert into public.gims_stock_balances(item_id,quantity) select id,0 from public.gims_items on conflict(item_id) do nothing;
